name: taqsi
description: "A simple Flutter weather app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  google_nav_bar: ^5.0.7
  lottie: ^3.3.1
  provider: ^6.1.5

  # Network & location
  http: ^1.4.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

  # Firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/

  fonts:
    - family: font1
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: font2
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        
    - family: font3
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
