// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChPz2LSIQe-Mw6gu-j3437iy7tBe4aCgc',
    appId: '1:416611905992:web:f9ba99997c34d1bd1d10fd',
    messagingSenderId: '416611905992',
    projectId: 'taqsi-3cc7f',
    authDomain: 'taqsi-3cc7f.firebaseapp.com',
    storageBucket: 'taqsi-3cc7f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBihk6ju__S6BfdcOSAiTOaMNDIXLFqeYo',
    appId: '1:416611905992:android:83a16180500a06081d10fd',
    messagingSenderId: '416611905992',
    projectId: 'taqsi-3cc7f',
    storageBucket: 'taqsi-3cc7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5QT4N_suwhOHQr29kwfPrcifhub8uel8',
    appId: '1:416611905992:ios:57cbc3467879690b1d10fd',
    messagingSenderId: '416611905992',
    projectId: 'taqsi-3cc7f',
    storageBucket: 'taqsi-3cc7f.firebasestorage.app',
    iosBundleId: 'com.example.taqsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5QT4N_suwhOHQr29kwfPrcifhub8uel8',
    appId: '1:416611905992:ios:57cbc3467879690b1d10fd',
    messagingSenderId: '416611905992',
    projectId: 'taqsi-3cc7f',
    storageBucket: 'taqsi-3cc7f.firebasestorage.app',
    iosBundleId: 'com.example.taqsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChPz2LSIQe-Mw6gu-j3437iy7tBe4aCgc',
    appId: '1:416611905992:web:b240db03274f56351d10fd',
    messagingSenderId: '416611905992',
    projectId: 'taqsi-3cc7f',
    authDomain: 'taqsi-3cc7f.firebaseapp.com',
    storageBucket: 'taqsi-3cc7f.firebasestorage.app',
  );
}
